replicaCount: 1

image:
  repository: shayca6/crypto-service
  tag: latest
  pullPolicy: Always

service:
  port: 5001

env:
  AUTH_VERIFY_URL: "http://auth-service:5000/auth/verify"
  COINGECKO_BASE_URL: "https://api.coingecko.com/api/v3"
  REQUEST_TIMEOUT: "5"

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 256Mi

