image:
  repository: shayca6/crypto-service
  tag: 24776e4

env:
  AUTH_VERIFY_URL: "http://auth-service:5000/auth/verify"
  COINGECKO_BASE_URL: "https://api.coingecko.com/api/v3"
  REQUEST_TIMEOUT: "5"

