apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: crypto-platform
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
    - host: crypto.apps.local
      http:
        paths:
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 5000
          - path: /crypto
            pathType: Prefix
            backend:
              service:
                name: crypto-service
                port:
                  number: 5001

